version: "3"
services:
  utils:
    build: ./utils
    ports:
      - 8080:8080
  app1:
    build: ./app1
    ports:
      - 8081:8080
    environment:
      - FAST_REFRESH=false
  app2:
    build: ./app2
    ports:
      - 8082:8080
    environment:
      - FAST_REFRESH=false
  root-config:
    build: ./root-config
    ports:
      - 9000:9000
